apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: msh-test

resources:
- ../../base





patches:
- path: patch/deployment.yaml
- path: patch/hpa.yaml
- path: patch/ingress.yaml



images:
- newTag: "latest"

# labels:
#   environment: dev
#   app: msh

secretGenerator:
- name: app-secret
  literals:
  - DATABASE_USER=dev-user
  - DATABASE_PASSWORD=devpassword
