apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: msh-test

resources:
- ../../base


patches:
- path: patch/deployment.yaml
- path: patch/hpa.yaml
- path: patch/ingress.yaml


images:
- name: datnd2711/pharmacy-fe
  newTag: "prod-0.110"


secretGenerator:
- name: my-dockerhub-secret
  literals:
  - username=datnd2711
  - password=234555axy
