apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: msh-sit

bases:
- ../../base

patchesStrategicMerge:
- patch/deployment.yaml

images:
- name: msh-application-sppl-shared-services
  newName: 851725622524.dkr.ecr.ap-southeast-1.amazonaws.com/msh-application-sppl-shared-services
  newTag: "v-893"

commonLabels:
  environment: sit
  app: msh-kustomize

secretGenerator:
- name: app-secret
  literals:
  - DATABASE_USER=sit-user
  - DATABASE_PASSWORD=sitpassword
