apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: msh-sit

resources:
- ../../base



patches:
- path: patch/deployment.yaml
- path: patch/hpa.yaml
- path: patch/ingress.yaml

images:
- name: msh-application-sppl-shared-services
  newName: 851725622524.dkr.ecr.ap-southeast-1.amazonaws.com/msh-application-sppl-shared-services
  newTag: "v-893"

secretGenerator:
- name: app-secret
  literals:
  - DATABASE_USER=sit-user
  - DATABASE_PASSWORD=sitpassword
