apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: msh-sit

resources:
- ../../base



patches:
- path: patch/deployment.yaml
- path: patch/hpa.yaml
- path: patch/ingress.yaml

images:
- newTag: "latest"

secretGenerator:
- name: app-secret
  literals:
  - DATABASE_USER=sit-user
  - DATABASE_PASSWORD=sitpassword
