apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: msh-hpa
spec:
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 120
