apiVersion: apps/v1
kind: Deployment
metadata:
  name: msh-kustomize
  labels:
    app: msh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msh
  template:
    metadata:
      labels:
        app: msh
    spec:
      containers:
      - name: msh-kustomize
        image: datnd2711/pharmacy-fe
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-dockerhub-secret
      volumeMounts:
      - name: var-volume
        mountPath: /var/log/nginx
        readOnly: false
      - name: var-volume
        mountPath: /var/cache/nginx
        readOnly: false
      - name: var-volume
        mountPath: /var/run
        readOnly: false
      - name: var-volume
        mountPath: /etc/nginx/conf.d/
        readOnly: false
